### PR TITLE
PHPSpec 3 upgrade

### PR DESCRIPTION
**Pull request by Sam-Burns**
Changes to the extension to work with PHPSpec 3, which is coming soon.

### CODE REVIEW

**Comment by Sam-Burns** [comment]
I'd suggest not merging this yet, as PHPSpec 3 isn't finalised yet, but I thought it might help to have a PR making the necessary changes for PHPSpec 3.

PHPSpec 3.0 will contain BC breaking changes which affect extension projects, including the renaming of several interfaces.  I'm getting your tests passing against `"phpspec/phpspec": "dev-master"` for now, just so you're in a strong position to have PHPSpec 3.0 support at the time it's released.

**Comment by BenConstable** [comment]
This is awesome, thanks very much! I'll try to take a look at it this weekend. What I'll likely do is move `master` over to support v3 going forwards, and possibly create a branch for v2 maintenance if it's needed.

👍

**Comment by Sam-Burns** [comment]
Thanks for letting me participate - I really like the tool you've built :-)

I've spoken to PHPSpec's lead maintainer @ciaranmcnulty, and it sounds like we may not be done making BC-breaking changes in the run-up to releasing `3.0`.  Perhaps the best thing is if I just keep this PR up-to-date and working as we go, and we can get in touch with you when `3.0` is out so you can merge it?

**Comment by ciaranmcnulty** [comment]
3.0.0 will be 'sometime in June' so depend on your release plan. If you don't want to do releases before then you could merge to `master` and keep patching as we break stuff, or some other branching strategy.

**Comment by BenConstable** [comment]
@Sam-Burns @ciaranmcnulty yep, that's fine. I'll likely do as I said and make `master` the branch for v3 going forward and keep a legacy branch for v2 support.

**Comment by dimitri-koenig** [comment]
Ping :-)

**Comment by Sam-Burns** [comment]
Alright, I've got Wednesday off; I'll have a look then

**Comment by BenConstable** [comment]
Apologies for the delay in getting to this. I've had a quick test locally and it looks like it's pretty much there - there are just a couple of additional changes required to get everything working.

@Sam-Burns thanks very much for again for the work you've put in so far. I've got some time tomorrow evening so I'll aim to get this merged into `master` then, and then add the additional fixes from there.

**Comment by BenConstable** [comment]
The PR's been merged and I've added some more fixes - v3 should now be supported! Let me know if it works for you. You'll need to update your `phpspec.yml`, so please check out the updated readme.

v3 support is on the `master` branch which is aliased to `3.x`. I'll release v3 of this package in the next few days if I don't hear about anything breaking.

**Pull request merged**
